# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/infoflow',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/infoflow',
                'lib_path': 'infoflow'},
  'syms': {'infoflow.core': {'infoflow.core.foo': ('core.html#foo', 'infoflow/core.py')}}}
