"""This module defines the classes we use to represent the PKM workflow."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_define_classes.ipynb.

# %% auto 0
__all__ = ['InformationType', 'Method', 'Phase', 'PhaseQuality', 'OrganizationSystem', 'InformationItem', 'Tool', 'Improvement']

# %% ../nbs/00_define_classes.ipynb 3
from enum import Enum
from typing import List, Union
from pydantic import BaseModel

# %% ../nbs/00_define_classes.ipynb 5
class InformationType(Enum):
    """Information content types that flow through the PKM workflow."""
    BOOK = "book"
    RESEARCH_PAPER = "research_paper"
    DOCUMENT = "document"
    ANNOTATION = "annotations&highlights"
    NOTE = "note"
    EMAIL = "email"
    DISCORD_MESSAGE = "discord_message"
    WEB_ARTICLE = "web_article"
    YOUTUBE_VIDEO = "youtube_video"
    PODCAST = "podcast"
    PRODUCT_IDEA = "product_idea"
    PROJECT_IDEA = "project_idea"

class Method(Enum):
    """How actions are performed - manually or automatically."""
    MANUAL = "manual"
    AUTOMATIC = "automatic"

class Phase(Enum):
    """The five phases of the PKM workflow."""
    COLLECT = "collect"
    RETRIEVE = "retrieve"
    CONSUME = "consume"
    EXTRACT = "extract"
    REFINE = "refine"

class PhaseQuality(Enum):
    """Quality rating for how well a tool performs in each phase."""
    NA = "na"
    BAD = "bad"
    OK = "ok"
    GREAT = "great"

class OrganizationSystem(Enum):
    """How tools organize and structure information."""
    TAGS = "tags"
    FOLDERS = "folders"
    LINKS = "links"
    JOHNNY_DECIMAL = "johnny_decimal"

# %% ../nbs/00_define_classes.ipynb 7
class InformationItem(BaseModel):
    """Represents an information item flowing through the PKM workflow."""
    info_type: InformationType
    method: list[Union[Method, None]]  # [collect, retrieve, consume, extract, refine]
    toolflow: list  # [collect, retrieve, consume, extract, refine]

class Tool(BaseModel):
    """Represents a PKM tool with supported information items."""
    name: str
    info_items: list[InformationItem]
    organization_system: list[OrganizationSystem]
    phase_quality: list[PhaseQuality]

class Improvement(BaseModel):
    """Tracks workflow improvements needed for better PKM effectiveness."""
    what: str
    why: str
    prio: int
    workflow_routes: list
