"""This module creates the different instances. In this module you can change the description of Tools, the flow of InformationItems. Add Tools and add InformationItems."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_create_instances.ipynb.

# %% auto 0
__all__ = ['web_article_item', 'annotation_item', 'note_item', 'book_item', 'podcast_item', 'research_paper_item',
           'document_item', 'youtube_video_item', 'reader', 'recall', 'readwise', 'obsidian', 'librarything', 'snipd',
           'neoreader', 'youtube']

# %% ../nbs/01_create_instances.ipynb 3
from .clasdef import *

# %% ../nbs/01_create_instances.ipynb 5
web_article_item = InformationItem(
    info_type=InformationType.WEB_ARTICLE,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=[("Reader", "Recall"), "Recall", "Reader", None, None]
)

# %% ../nbs/01_create_instances.ipynb 6
annotation_item = InformationItem(
    info_type=InformationType.ANNOTATION,
    method=[Method.AUTOMATIC, None, None, None, None],
    toolflow=[None, None, None, "Readwise", ("Recall", "Obsidian")]
)

note_item = InformationItem(
    info_type=InformationType.NOTE,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=[None, "Obsidian", "Obsidian", "Obsidian", "Obsidian"]
)
book_item = InformationItem(
    info_type=InformationType.BOOK,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=["LibraryThing", "LibraryThing", "NeoReader", "Readwise", "Obsidian"]
)

podcast_item = InformationItem(
    info_type=InformationType.PODCAST,
    method=[Method.AUTOMATIC, None, None, None, None],
    toolflow=["Snipd", "Snipd", "Snipd", "Readwise", "Obsidian"]
)

research_paper_item = InformationItem(
    info_type=InformationType.RESEARCH_PAPER,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=[("Recall", "NeoReader"), ("Recall", "NeoReader"), "NeoReader", "Readwise", ("Obsidian", "Recall")]
)

document_item = InformationItem(
    info_type=InformationType.DOCUMENT,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=["NeoReader", "NeoReader", "NeoReader", "Readwise", ("Obsidian", "Recall")]
)

youtube_video_item = InformationItem(
    info_type=InformationType.YOUTUBE_VIDEO,
    method=[Method.AUTOMATIC, None, None, None, None],
    toolflow=["YouTube", "YouTube", "YouTube", "Obsidian", "Obsidian"]
)

# %% ../nbs/01_create_instances.ipynb 8
reader = Tool(
    name="Reader",
    info_items=[web_article_item],
    organization_system=[OrganizationSystem.TAGS],
    phase_quality=[PhaseQuality.GREAT, PhaseQuality.BAD, PhaseQuality.GREAT, PhaseQuality.NA, PhaseQuality.NA]
)

recall = Tool(
    name="Recall",
    info_items=[web_article_item],
    organization_system=[OrganizationSystem.LINKS],
    phase_quality=[PhaseQuality.GREAT, PhaseQuality.GREAT, PhaseQuality.NA, PhaseQuality.NA, PhaseQuality.GREAT]
)

readwise = Tool(
    name="Readwise",
    info_items=[annotation_item],
    organization_system=[OrganizationSystem.TAGS],
    phase_quality=[PhaseQuality.NA, PhaseQuality.OK, PhaseQuality.NA, PhaseQuality.GREAT, PhaseQuality.OK]
)

obsidian = Tool(
    name="Obsidian",
    info_items=[annotation_item, note_item],
    organization_system=[OrganizationSystem.JOHNNY_DECIMAL, OrganizationSystem.LINKS],
    phase_quality=[PhaseQuality.NA, PhaseQuality.OK, PhaseQuality.OK, PhaseQuality.GREAT, PhaseQuality.GREAT]
)
librarything = Tool(
    name="LibraryThing",
    info_items=[book_item],
    organization_system=[OrganizationSystem.TAGS],
    phase_quality=[PhaseQuality.OK, PhaseQuality.BAD, PhaseQuality.NA, PhaseQuality.NA, PhaseQuality.NA]
)

snipd = Tool(
    name="Snipd",
    info_items=[podcast_item],
    organization_system=[OrganizationSystem.FOLDERS],
    phase_quality=[PhaseQuality.OK, PhaseQuality.BAD, PhaseQuality.GREAT, PhaseQuality.NA, PhaseQuality.NA]
)

neoreader = Tool(
    name="NeoReader",
    info_items=[book_item, research_paper_item, document_item],
    organization_system=[OrganizationSystem.FOLDERS],
    phase_quality=[PhaseQuality.OK, PhaseQuality.BAD, PhaseQuality.GREAT, PhaseQuality.NA, PhaseQuality.NA]
)

youtube = Tool(
    name="YouTube",
    info_items=[youtube_video_item],
    organization_system=[OrganizationSystem.FOLDERS],
    phase_quality=[PhaseQuality.OK, PhaseQuality.BAD, PhaseQuality.OK, PhaseQuality.NA, PhaseQuality.NA]
)


# %% ../nbs/01_create_instances.ipynb 9
web_article_item = InformationItem(
    info_type=InformationType.WEB_ARTICLE,
    method=[Method.MANUAL, None, None, None, None],
    toolflow=[("Reader", "Recall"), "Recall", "Reader", None, None]
)
