"""This module creates the different instances. In this module you can change the description of Tools, the flow of InformationItems. Add Tools and add InformationItems."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_create_instances.ipynb.

# %% auto 0
__all__ = ['tools_from_code', 'informationitems_from_code']

# %% ../nbs/01_create_instances.ipynb 4
from .classdb import *

# %% ../nbs/01_create_instances.ipynb 7
def tools_from_code():
    """Create all Tool instances as defined in the code."""
    reader = Tool(
        name="Reader",
        organization_system=[OrganizationSystem.TAGS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.GREAT,
            retrieve=PhaseQuality.BAD,
            consume=PhaseQuality.GREAT,
        )
    )

    recall = Tool(
        name="Recall",
        organization_system=[OrganizationSystem.LINKS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.GREAT,
            retrieve=PhaseQuality.GREAT,
            consume=PhaseQuality.NA,
            extract=PhaseQuality.NA,
            refine=PhaseQuality.GREAT
        )
    )

    readwise = Tool(
        name="Readwise",
        organization_system=[OrganizationSystem.TAGS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.NA,
            retrieve=PhaseQuality.OK,
            consume=PhaseQuality.NA,
            extract=PhaseQuality.GREAT,
            refine=PhaseQuality.OK
        )
    )

    obsidian = Tool(
        name="Obsidian",
        organization_system=[OrganizationSystem.JOHNNY_DECIMAL, OrganizationSystem.LINKS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.NA,
            retrieve=PhaseQuality.OK,
            consume=PhaseQuality.OK,
            extract=PhaseQuality.GREAT,
            refine=PhaseQuality.GREAT
        )
    )

    librarything = Tool(
        name="LibraryThing",
        organization_system=[OrganizationSystem.TAGS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.OK,
            retrieve=PhaseQuality.BAD,
            consume=PhaseQuality.NA,
            extract=PhaseQuality.NA,
            refine=PhaseQuality.NA
        )
    )

    snipd = Tool(
        name="Snipd",
        organization_system=[OrganizationSystem.FOLDERS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.OK,
            retrieve=PhaseQuality.BAD,
            consume=PhaseQuality.GREAT,
            extract=PhaseQuality.NA,
            refine=PhaseQuality.NA
        )
    )

    neoreader = Tool(
        name="NeoReader",
        organization_system=[OrganizationSystem.FOLDERS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.OK,
            retrieve=PhaseQuality.BAD,
            consume=PhaseQuality.GREAT,
            extract=PhaseQuality.NA,
            refine=PhaseQuality.NA
        )
    )

    youtube = Tool(
        name="YouTube",
        organization_system=[OrganizationSystem.FOLDERS],
        phase_quality=PhaseQualityData(
            collect=PhaseQuality.OK,
            retrieve=PhaseQuality.BAD,
            consume=PhaseQuality.OK,
            extract=PhaseQuality.NA,
            refine=PhaseQuality.NA
        )
    )


# %% ../nbs/01_create_instances.ipynb 12
def informationitems_from_code():
    """Create all InformationItem instances as defined in the code."""
    web_article_item = InformationItem(
        name="Web Article",
        info_type=InformationType.WEB_ARTICLE,
        method=PhaseMethodData(
            collect=Method.MANUAL
        ),
        toolflow=PhaseToolflowData(
            collect=("Reader", "Recall"),
            retrieve="Recall",
            consume="Reader"
        )
    )

    annotation_item = InformationItem(
        name="Annotation",
        info_type=InformationType.ANNOTATION,
        method=PhaseMethodData(
            collect=Method.AUTOMATIC
        ),
        toolflow=PhaseToolflowData(
            extract="Readwise",
            refine=("Recall", "Obsidian")
        )
    )

    note_item = InformationItem(
        name="Note",
        info_type=InformationType.NOTE,
        method=PhaseMethodData(
            collect=Method.MANUAL
        ),
        toolflow=PhaseToolflowData(
            retrieve="Obsidian",
            consume="Obsidian",
            extract="Obsidian",
            refine="Obsidian"
        )
    )

    book_item = InformationItem(
        name="Book",
        info_type=InformationType.BOOK,
        method=PhaseMethodData(
            collect=Method.MANUAL
        ),
        toolflow=PhaseToolflowData(
            collect="LibraryThing",
            retrieve="LibraryThing",
            consume="NeoReader",
            extract="Readwise",
            refine="Obsidian"
        )
    )

    podcast_item = InformationItem(
        name="Podcast",
        info_type=InformationType.PODCAST,
        method=PhaseMethodData(
            collect=Method.AUTOMATIC
        ),
        toolflow=PhaseToolflowData(
            collect="Snipd",
            retrieve="Snipd",
            consume="Snipd",
            extract="Readwise",
            refine="Obsidian"
        )
    )

    research_paper_item = InformationItem(
        name="Research Paper",
        info_type=InformationType.RESEARCH_PAPER,
        method=PhaseMethodData(
            collect=Method.MANUAL
        ),
        toolflow=PhaseToolflowData(
            collect=("Recall", "NeoReader"),
            retrieve=("Recall", "NeoReader"),
            consume="NeoReader",
            extract="Readwise",
            refine=("Obsidian", "Recall")
        )
    )

    document_item = InformationItem(
        name="Document",
        info_type=InformationType.DOCUMENT,
        method=PhaseMethodData(
            collect=Method.MANUAL
        ),
        toolflow=PhaseToolflowData(
            collect="NeoReader",
            retrieve="NeoReader",
            consume="NeoReader",
            extract="Readwise",
            refine=("Obsidian", "Recall")
        )
    )

    youtube_video_item = InformationItem(
        name="YouTube Video",
        info_type=InformationType.YOUTUBE_VIDEO,
        method=PhaseMethodData(
            collect=Method.AUTOMATIC
        ),
        toolflow=PhaseToolflowData(
            collect="YouTube",
            retrieve="YouTube",
            consume="YouTube",
            extract="Obsidian",
            refine="Obsidian"
        )
    )
