"""This module creates the workflow visualisation based on the instances and using the `graphiz` module."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_create_vizualisation.ipynb.

# %% auto 0
__all__ = ['get_info_items_for_tool', 'build_graphiz_from_instances', 'create_workflow_viz']

# %% ../nbs/02_create_vizualisation.ipynb 3
import graphviz
from .classdb import *
from .creinst import *

# %% ../nbs/02_create_vizualisation.ipynb 6
def get_info_items_for_tool(tool_name: str, info_items: dict[InformationItem]) -> dict[InformationItem]:
    """Filters all the instances of the class InformationItem based on which information items can be processed by the given tool."""
    if isinstance(info_items, dict): info_items = info_items.values()
    
    result = {}
    for item in info_items:
        for tool_entry in item.toolflow:
            if tool_entry is None: continue
            if isinstance(tool_entry, (list, tuple)):
                if tool_name in tool_entry:
                    result[item.name] = item
                    break
            elif tool_entry == tool_name:
                result[item.name] = item
                break
    
    return result

# %% ../nbs/02_create_vizualisation.ipynb 9
def build_graphiz_from_instances(info_items: dict[InformationItem], tools: dict[Tool]) -> graphviz.graphs.Digraph:
    """Create a graphviz visualisation based on the instances of the InformationItem class and their flow through the instances of the Tool class."""
    if isinstance(info_items, dict): info_items = list(info_items.values())
    elif not isinstance(info_items, list): info_items = [info_items]
    if isinstance(tools, dict): tools = list(tools.values())
    
    dot = graphviz.Digraph(comment='PKM Workflow')
    dot.attr(rankdir='TB')
    
    phases = ['collect', 'retrieve', 'consume', 'extract', 'refine']
    all_nodes = set()
    edges = {}
    
    quality_colors = {PhaseQuality.GREAT: 'lightgreen', PhaseQuality.OK: 'lightblue', PhaseQuality.BAD: 'orange', PhaseQuality.NA: 'lightgray'}
    
    for phase in phases:
        with dot.subgraph() as s:
            s.attr(rank='same')
            for info_item in info_items:
                i = phases.index(phase)
                if i < len(info_item.toolflow) and info_item.toolflow[i] is not None:
                    tool_entry = info_item.toolflow[i]
                    if isinstance(tool_entry, (list, tuple)): tools_in_phase = tool_entry
                    else: tools_in_phase = (tool_entry,)
                    
                    for tool_name in tools_in_phase:
                        if tool_name is not None:
                            node_id = f"{tool_name.lower()}_{phase}"
                            if node_id not in all_nodes:
                                tool = next((t for t in tools if t.name == tool_name), None)
                                color = quality_colors[tool.phase_quality[i]] if tool else 'white'
                                s.node(node_id, f"{tool_name}\n({phase})", shape='hexagon', fillcolor=color, style='filled')
                                all_nodes.add(node_id)
    
    with dot.subgraph() as s:
        s.attr(rank='same')
        for info_item in info_items:
            source_id = f"source_{info_item.info_type.value}"
            s.node(source_id, info_item.name, shape='box')
    
    for info_item in info_items:
        source_id = f"source_{info_item.info_type.value}"
        previous_nodes = [source_id]
        
        for i, tool_entry in enumerate(info_item.toolflow):
            if i < len(phases) and tool_entry is not None:
                phase = phases[i]
                current_nodes = []
                
                if isinstance(tool_entry, (list, tuple)): tools_in_phase = tool_entry
                else: tools_in_phase = (tool_entry,)
                
                for tool_name in tools_in_phase:
                    if tool_name is not None:
                        node_id = f"{tool_name.lower()}_{phase}"
                        current_nodes.append(node_id)
                        
                        for prev_node in previous_nodes:
                            edge_key = (prev_node, node_id)
                            if edge_key not in edges:
                                dot.edge(prev_node, node_id)
                                edges[edge_key] = True
                
                if current_nodes: previous_nodes = current_nodes
    
    return dot

# %% ../nbs/02_create_vizualisation.ipynb 10
def create_workflow_viz(items: None | InformationItem | dict[str, InformationItem] = None,
                        tools: None | Tool | dict[str, Tool] =None,
                        tool_filter: None | str = None) -> graphviz.graphs.Digraph:
    """Create workflow visualization with flexible filtering options."""
    # Default to all items and tools if none specified
    if items is None: items = InformationItem.get_instances()
    if tools is None: tools = Tool.get_instances()
    
    # Filter by tool if specified
    if tool_filter:
        items = get_info_items_for_tool(tool_filter, items)
    
    return build_graphiz_from_instances(items, tools)
