"""This module creates the `FastHTML` webapplication and starts the server."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_create_webapp.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_create_webapp.ipynb 3
from fasthtml.common import *
from monsterui.all import *

from .clasdef import *
from .creinst import *
from .viz import *
